name: Create Deploy Preview

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]

env:
  PROJECT: ${{ github.event.repository.name }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  PR_NUMBER: ${{ github.event.number }}
  DOMAIN: rachelel.xyz
  AWS_REGION: us-east-2
  ECR_REPOSITORY: campfire-ecr
  ECS_CLUSTER: demo-app-3
  PORT: 8080
  ROLE_ARN: arn:aws:iam::903035593422:role/CampfireECSTaskExecutionRole
  LB_NAME: campfire
  SUBNET_NAME: subnet-037753d31df2d88b6
  SG_NAME: sg-01f0c9ff3bcdc87cb

permissions:
  contents: read

jobs:
  deploy_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.COMMIT_ID }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve Campfire Bot credentials from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            campfire/secrets/private-key
            campfire/secrets/github-app-secrets
          parse-json-secrets: true

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.CAMPFIRE_SECRETS_GITHUB_APP_SECRETS_APP_ID }}
          private-key: ${{ env.CAMPFIRE_SECRETS_PRIVATE_KEY }}

      - name: Comment Build Status as Started
        uses: hasura/comment-progress@v2.3.0
        with:
          id: status-comment
          github-token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          number: ${{ env.PR_NUMBER }}
          message: "| Status | Message |\n|--------|-------|\n| \U000026FA | Your Campfire deploy preview is currently being built and deployed to your AWS |"
          append: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR Registry Environment Variable
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Deploy App to Amazon ECS
        id: deploy-preview-app
        uses: ./.github/actions/deploy-preview

      - name: Comment Build Status as Completed
        uses: hasura/comment-progress@v2.3.0
        with:
          id: status-comment
          github-token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          number: ${{ env.PR_NUMBER }}
          message: "| \U0001f525 | Your Campfire has started successfully. Visit your deploy preview here: ${{ steps.deploy-preview-app.outputs.url }} |"
          append: true
