name: "Update Preview App"
on:
  pull_request:
    types: [synchronize]

env:
  PROJECT: ${{ github.event.repository.name }}
  COMMIT_ID: ${{ github.event.pull_request.head.sha }}
  PR_NUMBER: ${{ github.event.number }}
  DOMAIN: rachelel.xyz
  AWS_REGION: us-east-2
  ECR_REPOSITORY: campfire-ecr
  ECS_CLUSTER: demo-app
  PORT: 8080
  ROLE_ARN: arn:aws:iam::903035593422:role/CampfireECSTaskExecutionRole
  LB_NAME: campfire
  SUBNET_NAME: subnet-01c4fdc08e544242a
  SG_NAME: sg-084b00cce822002e4

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve Campfire Bot credentials from AWS
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            campfire/secrets/private-key
            campfire/secrets/github-app-secrets
          parse-json-secrets: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: set ECR Registry Environment Variable
        run: |
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Delete App on Amazon ECS
        id: delete-preview
        uses: ./.github/actions/delete-preview

      - name: Deploy Updated App to Amazon ECS
        id: deploy-app
        uses: ./.github/actions/deploy-preview

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ env.CAMPFIRE_SECRETS_GITHUB_APP_SECRETS_APP_ID }}
          private-key: ${{ env.CAMPFIRE_SECRETS_PRIVATE_KEY }}

      - name: Comment Status as Updated
        uses: hasura/comment-progress@v2.3.0
        with:
          id: status-comment
          github-token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          number: ${{ env.PR_NUMBER }}
          message: "| Status | Message |\n|--------|-------|\n| \U00002757 | Your preview has been updated with the lastest commit. Visit your super cool amazing preview app here ${{ steps.deploy-app.outputs.url }} |"
          append: false
